In [3]:
import torch

print("PyTorch version:", torch.__version__)

PyTorch version: 2.7.1+cu118


## Understanding the Tensor

Tensor is difference from scalar, vector, and matrix because it can represent more dimensions from 0, to n. while matrix or vector can represent 2 or matrix.

You can refer more description of tensor and other fundamental operation in PyTorch from: https://www.learnpytorch.io/00_pytorch_fundamentals/

## Creating Tensors

A scalar is the single number, so it have zero dimension tensor.

In [3]:
# scalar
scalar = torch.tensor(9)
scalar

tensor(9)

In [6]:
scalar.ndim

0

In [7]:
scalar.shape

torch.Size([])

In [ ]:
# Get the python integer value from the scalar tensor, this operation work only for scalar tensor
scalar.item()

9

Vector is single dimension tensor that can contain many multiple numbers.

In [11]:
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [14]:
vector.ndim

1

In [ ]:
# this shape ilustrates the amount of element inside the vector or current dimension.
vector.shape

torch.Size([3])

Matrix is two dimension tensor.

In [16]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
matrix.ndim

2

In [18]:
matrix.shape

torch.Size([3, 3])

The shape of the matrix is [3, 3] because matrix is three elements deep and three wide.
What if we shrink the element to this:

In [23]:
matrix = torch.tensor([[1, 2], [4, 5], [7, 8]])
matrix.shape

torch.Size([3, 2])

In [25]:
matrix.ndim

2

In [33]:
matrix = torch.tensor(
    [
        [
            [1, 2], 
            [4, 5], 
            [7, 8],
            [7, 8],
        ],
        [
            [1, 2], 
            [4, 5], 
            [7, 8],
            [7, 8],
        ],
        [
            [1, 2], 
            [4, 5], 
            [7, 8],
            [7, 8],
        ],
        
    ]
    )
matrix.shape

torch.Size([3, 4, 2])

In [29]:
matrix.ndim

3

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`
Torch Random Tensors:https://docs.pytorch.org/docs/stable/generated/torch.rand.html#torch-rand

In [42]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4152, 0.1565, 0.7456, 0.5493],
        [0.4066, 0.5307, 0.2377, 0.0590],
        [0.0125, 0.1524, 0.0519, 0.8404]])

In [37]:
random_tensor.ndim,random_tensor.shape

(2, torch.Size([3, 4]))

In [38]:
random_tensor = torch.rand(3, 254, 254)
random_tensor

tensor([[[0.4702, 0.6995, 0.8378,  ..., 0.4657, 0.4709, 0.3552],
         [0.7214, 0.2022, 0.8042,  ..., 0.2727, 0.7618, 0.6621],
         [0.7409, 0.8397, 0.6620,  ..., 0.8972, 0.7137, 0.5146],
         ...,
         [0.1571, 0.1176, 0.9581,  ..., 0.2756, 0.2053, 0.6191],
         [0.9383, 0.9981, 0.5570,  ..., 0.7450, 0.9995, 0.8800],
         [0.3169, 0.6501, 0.2547,  ..., 0.4988, 0.6797, 0.2915]],

        [[0.6926, 0.2761, 0.1472,  ..., 0.1120, 0.5826, 0.2622],
         [0.3587, 0.2071, 0.0397,  ..., 0.7490, 0.5807, 0.2322],
         [0.5252, 0.9178, 0.9664,  ..., 0.6350, 0.1628, 0.1435],
         ...,
         [0.2659, 0.3539, 0.5036,  ..., 0.6384, 0.1689, 0.3617],
         [0.3611, 0.7942, 0.9333,  ..., 0.1765, 0.2341, 0.9283],
         [0.7921, 0.9334, 0.5869,  ..., 0.9729, 0.4521, 0.7652]],

        [[0.0753, 0.5587, 0.7045,  ..., 0.8291, 0.4679, 0.3728],
         [0.2723, 0.7811, 0.5830,  ..., 0.4501, 0.8686, 0.3911],
         [0.3052, 0.8536, 0.5785,  ..., 0.7414, 0.7908, 0.

In [40]:
random_tensor.ndim,random_tensor.shape

(3, torch.Size([3, 254, 254]))

## Zeros and ones

In [41]:
# Create a tensor with all zeros
zeros_tensor = torch.zeros(3, 4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [44]:
# Create a tensor with all ones
ones_tensor = torch.ones(3, 4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [46]:
ones_tensor.dtype

torch.float32

In [43]:
zeros_tensor * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensors-like

In [57]:
# use torch.range() if this function deprecated, use torch.arange()
torch.range(0, 10)

/var/folders/dr/fn2_r29930s6nq_wqwxq_ckm0000gn/T/ipykernel_48780/558156120.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [58]:
one_to_ten = torch.arange(start=0, end=10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [59]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros # we got the same shape and dtype as one_to_ten

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor 
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], 
    dtype=torch.float16, # Default is float32
    device=None, # None means CPU. What device that tensor will be stored on
    requires_grad=False # Track gradients for this tensor (default is False)
    )
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [62]:
float_32_tensor.dtype

torch.float32

The output is still float32 because the default value of pytorch is float32
<br>
The different between float32 and float 16 or other is the number which float32 will store in memory than float16 or lower which meaning that float32 will compute lower than float16. If develop model that need very high accuracy float32 might be the great choice.

In [68]:
float_16_tensors = float_32_tensor.type(torch.float16)
float_16_tensors

tensor([3., 6., 9.], dtype=torch.float16)

In [69]:
float_32_tensor * float_16_tensors

tensor([ 9., 36., 81.], dtype=torch.float16)

In [73]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [72]:
int_32_tensor * float_16_tensors

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors
1. Tensors not right datatype. (get datatypes - tensor.dtype)
2. Tensors not right shape. (get shape - tensor.shape)
3. Tensors not on the right device. (get device - tensor.device)

In [74]:
# create some tensors
some_tensor = torch.tensor([2,3])
some_tensor

tensor([2, 3])

In [75]:
print("datatype of some_tensor:", some_tensor.dtype)
print("shape of some_tensor:", some_tensor.shape)
print("device of some_tensor:", some_tensor.device)

datatype of some_tensor: torch.int64
shape of some_tensor: torch.Size([2])
device of some_tensor: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element wise)
* Division
* Matrix multiplication

In [78]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [79]:
# multiply the tensor by 10
tensor * 10

tensor([10, 20, 30])

In [80]:
# subtract 10 from the tensor
tensor - 10

tensor([-9, -8, -7])

In [81]:
# divide the tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [82]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)  # multiply

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplcation needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)`  will work
* `(3, 2) @ (2, 3)`  will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [88]:
# illustrate error of shape mismatch
torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [84]:
# Matrix multiplication
torch.matmul(tensor, tensor)  # matrix multiplication

tensor(14)

In [85]:
tensor

tensor([1, 2, 3])

### One of the most common errors in deep learning: shape errors

In [92]:
tensor_A = torch.tensor([[1, 2], 
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

torch.mm(tensor_A, tensor_B)  # matrix multiplication

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [94]:
# Transpose a tensor
tensor_B.T  # transpose of tensor_B

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [93]:
torch.mm(tensor_A, tensor_B.T)  # matrix multiplication with transpose

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [113]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [99]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [100]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [102]:
x.dtype

torch.int64

In [106]:
# Find the mean - note: torch.mean() requires float tensors
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [107]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [116]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [117]:
# Find the position in tensor that has the minimum value with argmin() -> return the index of the minimum value
x.argmin()

tensor(0)

In [118]:
x[0]

tensor(1)

In [119]:
# Find the position in tensor that has the maximum value with argmax() -> return the index of the maximum value
x.argmax()

tensor(9)

In [120]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [141]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape # 10 elements in the tensor

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [142]:
x_reshaped = x.reshape(1, 9) # 9 * 1 = 10 need to be the same as the original tensor size
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [147]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [148]:
# Changeing z changes x (because they share the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [158]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [160]:
# squeeze - remove all dimensions of size 1
x = torch.zeros(2, 1, 2, 1, 2)
x.shape

torch.Size([2, 1, 2, 1, 2])

In [161]:
y = torch.squeeze(x)
y.shape

torch.Size([2, 2, 2])

In [162]:
y = torch.squeeze(x, 0)
y.shape

torch.Size([2, 1, 2, 1, 2])

In [166]:
y = torch.squeeze(x, 1)
y.shape

torch.Size([2, 2, 1, 2])

In [170]:
x_reshaped
x_reshaped.shape

torch.Size([1, 9])

In [172]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [174]:
# torch.unsqueeze() - add a dimension of size 1 to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"New tensor: {x_unsqueezed}")
print(f"new tensor shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
new tensor shape: torch.Size([9, 1])


In [ ]:
# torch.permute() - rearrange the order of a target tnesor in a specified order 
# often used in image data
x = torch.rand(2, 3, 5)
x.shape

torch.Size([2, 3, 5])

In [177]:
torch.permute(x, (2, 0, 1)).shape  # change the order of dimensions

torch.Size([5, 2, 3])

In [179]:
x_original = torch.rand(224, 224, 3)  # height, width, color_channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # color_channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [190]:
x_original[0, 0, 0] = 0.6666
x_permuted

tensor([[[0.6666, 0.6783, 0.9261,  ..., 0.9460, 0.9559, 0.4680],
         [0.6721, 0.7860, 0.7761,  ..., 0.3166, 0.0214, 0.5446],
         [0.3436, 0.1851, 0.4135,  ..., 0.6925, 0.2374, 0.4489],
         ...,
         [0.2865, 0.5333, 0.3209,  ..., 0.7363, 0.4633, 0.1089],
         [0.7115, 0.7547, 0.9695,  ..., 0.4826, 0.6102, 0.3398],
         [0.0225, 0.0489, 0.3057,  ..., 0.0445, 0.3262, 0.6813]],

        [[0.4579, 0.2036, 0.4027,  ..., 0.5964, 0.1889, 0.5637],
         [0.2286, 0.5608, 0.4086,  ..., 0.9377, 0.8596, 0.0107],
         [0.9846, 0.0612, 0.7889,  ..., 0.9780, 0.0048, 0.6083],
         ...,
         [0.4136, 0.8130, 0.9166,  ..., 0.8352, 0.3468, 0.1092],
         [0.7541, 0.5513, 0.4765,  ..., 0.1137, 0.0379, 0.3266],
         [0.1157, 0.0153, 0.5014,  ..., 0.5475, 0.9747, 0.5223]],

        [[0.5434, 0.5445, 0.4795,  ..., 0.6406, 0.0533, 0.8700],
         [0.0636, 0.6459, 0.4684,  ..., 0.8405, 0.6123, 0.3717],
         [0.2433, 0.9649, 0.3200,  ..., 0.0388, 0.6357, 0.

## Indexing (seecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy


In [191]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0] # index on the first dimension

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [195]:
# Let's index on the most inner bracket (dim=2)
x[0, 0, 0]  # index on the last dimension

tensor(1)

In [196]:
# You can also use ":" to select all values in a dimension
x[:, 0]

tensor([[1, 2, 3]])

In [202]:
# get all values of 0th and 1st dimensions but only the 1st value of the last dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension, but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [205]:
# Get index 0 of 0th and 1st dimension and all values of the last dimension
x[0, 0, :]

tensor([1, 2, 3])

In [208]:
# Index on x to return 9
x[:, 2, 2]

tensor([9])

In [209]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch Tensor & NumPy

NumPy is a popular scientific Python numerical computing library.
Because of this, PyTorch has funtionality to interact with it.
* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [213]:
# NumPy Array to Tensor
import numpy as np
import torch

array = np.arange(1., 8.) # defaut dtype is float64
tensor = torch.from_numpy(array).type(torch.float32)  # convert to float32 tensor
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [214]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [216]:
# Change the value of array, What will this do to `tensor`?
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

So array and tensor doesn't share the memory

In [217]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()  # convert to numpy array
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

since pytorch have dtype is float 32, so when convert to numpy it will get the pytorch default value

In [218]:
# Change the tensor, What happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

So they don't share memory

## Reproducbility (trying take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better represen
tations of data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness



In [ ]:
import torch

#Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B) 
print(random_tensor_A == random_tensor_B) 

tensor([[0.4566, 0.5275, 0.3903, 0.5066],
        [0.5441, 0.6262, 0.3359, 0.2589],
        [0.8291, 0.2653, 0.3055, 0.0012]])
tensor([[0.4255, 0.8876, 0.9511, 0.7919],
        [0.7842, 0.8883, 0.3934, 0.4504],
        [0.1135, 0.8835, 0.9264, 0.8968]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [4]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # only work in one block of code
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)  # should be all False since they are random

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra Resources for reproducibility:
* https://docs.pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed


## Running tensors and PyTorch objects on the GPU (and making faster computations)

GPU = Faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

### 1. Getting a GPU

1. Easiest - Use Goodle Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit setup and requires the inverstment of purchasing a GPU, there's lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this refer to PyTorch setup documentation.

### 2. Check for GPU access with PyTorch

In [5]:
# Check for GPU access with PTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code

In [6]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda


In [7]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The  reason we want out tensors/models on the GPU is because using a GPU results in faster computations

In [8]:
# create a tensor (default is on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

### 4. Moving tensors back to the CPU

In [10]:
# If tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()  # this will raise an error if you have GPU access

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [11]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu, tensor_back_on_cpu.device

(array([1, 2, 3]), 'cpu')

In [12]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-Curriculum

see exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/